/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImportRouteImport } from './routes/import'
import { Route as GroceryRouteImport } from './routes/grocery'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesScanRouteImport } from './routes/recipes.scan'
import { Route as RecipesNewRouteImport } from './routes/recipes.new'
import { Route as RecipesIdRouteImport } from './routes/recipes.$id'
import { Route as BooksIdRouteImport } from './routes/books.$id'
import { Route as RecipesIdCookRouteImport } from './routes/recipes.$id.cook'
import { Route as ApiPublicRecipeShareRouteImport } from './routes/api/public/recipe-share'

const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryRoute = GroceryRouteImport.update({
  id: '/grocery',
  path: '/grocery',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesScanRoute = RecipesScanRouteImport.update({
  id: '/recipes/scan',
  path: '/recipes/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIdRoute = BooksIdRouteImport.update({
  id: '/books/$id',
  path: '/books/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdCookRoute = RecipesIdCookRouteImport.update({
  id: '/cook',
  path: '/cook',
  getParentRoute: () => RecipesIdRoute,
} as any)
const ApiPublicRecipeShareRoute = ApiPublicRecipeShareRouteImport.update({
  id: '/api/public/recipe-share',
  path: '/api/public/recipe-share',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/grocery': typeof GroceryRoute
  '/import': typeof ImportRoute
  '/books/$id': typeof BooksIdRoute
  '/recipes/$id': typeof RecipesIdRouteWithChildren
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/scan': typeof RecipesScanRoute
  '/api/public/recipe-share': typeof ApiPublicRecipeShareRoute
  '/recipes/$id/cook': typeof RecipesIdCookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/grocery': typeof GroceryRoute
  '/import': typeof ImportRoute
  '/books/$id': typeof BooksIdRoute
  '/recipes/$id': typeof RecipesIdRouteWithChildren
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/scan': typeof RecipesScanRoute
  '/api/public/recipe-share': typeof ApiPublicRecipeShareRoute
  '/recipes/$id/cook': typeof RecipesIdCookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/grocery': typeof GroceryRoute
  '/import': typeof ImportRoute
  '/books/$id': typeof BooksIdRoute
  '/recipes/$id': typeof RecipesIdRouteWithChildren
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/scan': typeof RecipesScanRoute
  '/api/public/recipe-share': typeof ApiPublicRecipeShareRoute
  '/recipes/$id/cook': typeof RecipesIdCookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/grocery'
    | '/import'
    | '/books/$id'
    | '/recipes/$id'
    | '/recipes/new'
    | '/recipes/scan'
    | '/api/public/recipe-share'
    | '/recipes/$id/cook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/grocery'
    | '/import'
    | '/books/$id'
    | '/recipes/$id'
    | '/recipes/new'
    | '/recipes/scan'
    | '/api/public/recipe-share'
    | '/recipes/$id/cook'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/grocery'
    | '/import'
    | '/books/$id'
    | '/recipes/$id'
    | '/recipes/new'
    | '/recipes/scan'
    | '/api/public/recipe-share'
    | '/recipes/$id/cook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  GroceryRoute: typeof GroceryRoute
  ImportRoute: typeof ImportRoute
  BooksIdRoute: typeof BooksIdRoute
  RecipesIdRoute: typeof RecipesIdRouteWithChildren
  RecipesNewRoute: typeof RecipesNewRoute
  RecipesScanRoute: typeof RecipesScanRoute
  ApiPublicRecipeShareRoute: typeof ApiPublicRecipeShareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery': {
      id: '/grocery'
      path: '/grocery'
      fullPath: '/grocery'
      preLoaderRoute: typeof GroceryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/scan': {
      id: '/recipes/scan'
      path: '/recipes/scan'
      fullPath: '/recipes/scan'
      preLoaderRoute: typeof RecipesScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$id': {
      id: '/books/$id'
      path: '/books/$id'
      fullPath: '/books/$id'
      preLoaderRoute: typeof BooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id/cook': {
      id: '/recipes/$id/cook'
      path: '/cook'
      fullPath: '/recipes/$id/cook'
      preLoaderRoute: typeof RecipesIdCookRouteImport
      parentRoute: typeof RecipesIdRoute
    }
    '/api/public/recipe-share': {
      id: '/api/public/recipe-share'
      path: '/api/public/recipe-share'
      fullPath: '/api/public/recipe-share'
      preLoaderRoute: typeof ApiPublicRecipeShareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RecipesIdRouteChildren {
  RecipesIdCookRoute: typeof RecipesIdCookRoute
}

const RecipesIdRouteChildren: RecipesIdRouteChildren = {
  RecipesIdCookRoute: RecipesIdCookRoute,
}

const RecipesIdRouteWithChildren = RecipesIdRoute._addFileChildren(
  RecipesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  GroceryRoute: GroceryRoute,
  ImportRoute: ImportRoute,
  BooksIdRoute: BooksIdRoute,
  RecipesIdRoute: RecipesIdRouteWithChildren,
  RecipesNewRoute: RecipesNewRoute,
  RecipesScanRoute: RecipesScanRoute,
  ApiPublicRecipeShareRoute: ApiPublicRecipeShareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
